FROM python:2.7
MAINTAINER XiVO Team "dev@avencall.com"

# Install xivo-tools
WORKDIR /root
RUN git clone "git://github.com/xivo-pbx/xivo-tools"
WORKDIR xivo-tools
RUN python setup.py install
RUN pip install kombu

WORKDIR scripts
CMD python recv-bus-event
