#!/bin/bash

SERVICES="ssh nginx"

function start {
    for service in $SERVICES
    do
        echo "Launch $service ..."
        service $service start
    done
}

# Launching xivo-dird
start
xivo-amid -d -f -u www-data
